# Edge Safety Monitor - Dataset Configuration
# YOLOv8 format

# Paths (relative to this file)
path: ../data  # dataset root dir
train: processed/train/images  # train images
val: processed/val/images  # validation images
test: processed/test/images  # test images (optional)

# Classes
names:
  0: person
  1: helmet
  2: no_helmet
  3: vest
  4: no_vest
  5: phone
  6: drowsy
  7: alert

# Number of classes
nc: 8

# Dataset info
dataset_name: Edge Safety Monitor Dataset
version: 1.0
created: 2025-10-12
author: Siddique Akber

# Training parameters (recommended)
epochs: 100
batch: 16
imgsz: 640
patience: 50
